<table class="table table-striped">

            <?php
            foreach($all_meter as $m)
            {
              
              echo "
                <tr>
                  <td>Date_Time</td><td>$m->Date_Time</td>
                <tr>
                  <td>Device_ID</td><td>$m->Device_ID</td>
                <tr>
                  <td>Current_A</td><td>$m->Current_A</td>
                <tr>
                  <td>Current_B</td><td>$m->Current_B</td>
                <tr>
                  <td>Current_C</td><td>$m->Current_C</td>
                <tr>
                  <td>Current_N</td><td>$m->Current_N</td>
                <tr>
                  <td>Current_G</td><td>$m->Current_G</td>
                <tr>
                  <td>Current_Avg</td><td>$m->Current_Avg</td>
                <tr>
                  <td>Voltage_A_B</td><td>$m->Voltage_A_B</td>
                <tr>
                  <td>Voltage_B_C</td><td>$m->Voltage_B_C</td>
                <tr>
                  <td>Voltage_C_A</td><td>$m->Voltage_C_A</td>
                <tr>
                  <td>Voltage_L_L_Avg</td><td>$m->Voltage_L_L_Avg</td>
                <tr>
                  <td>Voltage_A_N</td><td>$m->Voltage_A_N</td>
                <tr>
                  <td>Voltage_B_N</td><td>$m->Voltage_B_N</td>
                <tr>
                  <td>Voltage_C_N</td><td>$m->Voltage_C_N</td>
                <tr>
                  <td>Voltage_L_N_Avg</td><td>$m->Voltage_L_N_Avg</td>
                <tr>
                  <td>Active_Power_A</td><td>$m->Active_Power_A</td>
                <tr>
                  <td>Active_Power_B</td><td>$m->Active_Power_B</td>
                <tr>
                  <td>Active_Power_C</td><td>$m->Active_Power_C</td>
                <tr>
                  <td>Active_Power_Total</td><td>$m->Active_Power_Total</td>
                <tr>
                  <td>Reactive_Power_A</td><td>$m->Reactive_Power_A</td>
                <tr>
                  <td>Reactive_Power_B</td><td>$m->Reactive_Power_B</td>
                <tr>
                  <td>Reactive_Power_C</td><td>$m->Reactive_Power_C</td>
                <tr>
                  <td>Reactive_Power_Total</td><td>$m->Reactive_Power_Total</td>
                <tr>
                  <td>Apparent_Power_A</td><td>$m->Apparent_Power_A</td>
                <tr>
                  <td>Apparent_Power_B</td><td>$m->Apparent_Power_B</td>
                <tr>
                  <td>Apparent_Power_C</td><td>$m->Apparent_Power_C</td>
                <tr>
                  <td>Apparent_Power_Total</td><td>$m->Apparent_Power_Total</td>
                <tr>
                  <td>Power_Factor_A</td><td>$m->Power_Factor_A</td>
                <tr>
                  <td>Power_Factor_B</td><td>$m->Power_Factor_B</td>
                <tr>
                  <td>Power_Factor_C</td><td>$m->Power_Factor_C</td>
                <tr>
                  <td>Power_Factor_Total</td><td>$m->Power_Factor_Total</td>
                <tr>
                  <td>Displacement_Power_Factor_A</td><td>$m->Displacement_Power_Factor_A</td>
                <tr>
                  <td>Displacement_Power_Factor_B</td><td>$m->Displacement_Power_Factor_B</td>
                <tr>
                  <td>Displacement_Power_Factor_C</td><td>$m->Displacement_Power_Factor_C</td>
                <tr>
                  <td>Displacement_Power_Factor_Total</td><td>$m->Displacement_Power_Factor_Total</td>
                <tr>
                  <td>Frequency</td><td>$m->Frequency</td>
                <tr>
                  <td>Energy</td><td>$m->Energy</td>
              ";

            }
            ?>
</table>